apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: infra-tools
spec:
  project: default

  destination:
    namespace: infra-tools
    server: https://kubernetes.default.svc

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "75.16.1"

    helm:
      valuesObject:
        crds:
          enabled: false

        nameOverride: prometheus-operator

        defaultRules:
          create: true
          rules:
            cpu: true
            memory: true

        prometheus:
          ingress:
            enabled: false
          thanosService:
            enabled: false
          thanosIngress:
            enabled: false
          prometheusSpec:
            serviceMonitorSelector: {}
            serviceMonitorSelectorNilUsesHelmValues: false
            retention: 2d

        kubelet:
          enabled: true
          serviceMonitor:
            enabled: true

        alertmanager:
          enabled: true
          ingress:
            enabled: false
          alertmanagerSpec:
            forceEnableClusterMode: true

        grafana:
          ingress:
            enabled: false
          adminPassword: prom-operator

        prometheusOperator:
          admissionWebhooks:
            enabled: false
            patch:
              enabled: false
            certManager:
              enabled: false
            autoGenerateCert: false
            tls:
              enabled: false

        kube-state-metrics:
          prometheus:
            monitor:
              enabled: true

        prometheus-node-exporter:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
