replicaCount: 1

image:
  repository: 650830975789.dkr.ecr.eu-north-1.amazonaws.com/mlops-inference
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

mlflow:
  trackingUri: "http://mlflow.mlflow.svc.cluster.local:5000"
  modelName: "iris-logistic-regression"
  modelAlias: "production"

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi

serviceMonitor:
  enabled: true
  interval: 15s
